### ISSUE TITLE
Look into supporting gtkmm4

### ISSUE THREAD

**Issue by tschoonj** [tschoonj/gtkmm-plplot#28]
gtkmm4 was released today... time to have a look at it.

**Comment by AlexB67** [comment]
Quite a bit of work. I migrated today, almost done, 5 hours so far for my trivial plotting app . Quite a bit of reading around, but getting there :) Event handling has change a lot.

**Comment by tschoonj** [comment]
Yeah looks like a lot of fun... I am in no hurry to start the migration here so if you would like to give it a try yourself, feel free to do so 😄

**Comment by AlexB67** [comment]
I am beginning to find a few bugs now too. Could be because of my
source build from tarballs,  but in conclusion I don't trust it yet for
prime time. themeing is broken, intelligent window placement is awful
,always at 0,0 because they removed it (sighs).  Mouse events (now in the
form of gesture events  to support touch screens) are sluggish and stop
responding with cairo surfaces occasionally for some unknown reason. Long
live gtkmm3 :D

**Comment by tschoonj** [comment]
This looks relevant: https://blog.gtk.org/2020/04/24/custom-widgets-in-gtk-4-drawing/

**Comment by AlexB67** [comment]
Got all my cairo code workingn gtkmm4. As long as gtkmm is build against gtk4.0.3 or later most issues I came across have been fixed. yeah have0n't used the snapshots yet. The porting was mostly quite trivial. Most drawing code remained the same. Events changed .. a lot. I don't have a touch screen, but in theory I can zoom with swipe gestures now too :). Uploading next week after Fedora 34 release so I can rebuild against the latest gtk4.
